version: 2
mergeable:
  - when: pull_request.*
    name: "Require approval for major/regular changes"
    filter:
      - do: payload
        pull_request:
          must_include:
            - "change_classification:major"
            - "change_classification:regular"
    validate:
      - do: approvals
        required: 1
    fail:
      - do: comment
        payload: "This PR requires approval due to major/regular change classification."

  - when: pull_request.*
    name: "Allow auto-merge for minor/emergency changes"
    filter:
      - do: payload
        pull_request:
          must_include:
            - "change_classification:minor"
            - "change_classification:emergency"
    validate:
      - do: approvals
        required: 0
    pass:
      - do: comment
        payload: "This PR can be auto-merged due to minor/emergency change classification."

  - when: pull_request.*
    name: "Require change classification label"
    filter:
      - do: payload
        pull_request:
          must_exclude:
          - "change_classification:major"
          - "change_classification:regular"
          - "change_classification:minor"
          - "change_classification:emergency"
          - "change_type:major"
          - "change_type:regular"
          - "change_type:minor"
          - "change_type:emergency"
    validate: []
    fail:
      - do: comment
        payload: "PR must have a change_classification or change_type label to be merged."
