version: 2
mergeable:
  - when: pull_request.*
    name: "Require approval for major/regular changes"
    filter:
      - do: payload
        pull_request:
          labels:
            must_include:
              regex: "change_classification:major|change_classification:regular"
              key: name
    validate:
      - do: approvals
        required: 1
    fail:
      - do: comment
        payload: "This PR requires approval due to major/regular change classification."

  - when: pull_request.*
    name: "Allow auto-merge for minor/emergency changes"
    filter:
      - do: payload
        pull_request:
          labels:
            must_include:
              regex: "change_classification:minor|change_classification:emergency"
              key: name
    validate:
      - do: approvals
        required: 0
    pass:
      - do: comment
        payload: "This PR can be auto-merged due to minor/emergency change classification."

  - when: pull_request.*
    name: "Require change classification label"
    validate:
      - do: label
        and:
          - do: label
            must_include:
              regex: "change_classification"
          - do: label
            must_exclude:
              regex: "change_type"
    fail:
      - do: comment
        payload: "PR must have a change_classification or change_type label to be merged."
